services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    networks:
      - piscinedsNet

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - piscinedsNet

networks:
  piscinedsNet:
    name: piscinedsNet
    driver: bridge

volumes:
  database:
    name: piscineds_db