services:
  postgres:
    container_name: postgres_db
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    restart: always
    environment:
      POSTGRES_USER: xmatute-
      POSTGRES_DB: piscineds
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
      
    # env_file:
    #   - .env

volumes:
  database:
    name: piscineds_db
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/srcs/database
      o: bind